### ISSUE TITLE
Heap is not set when mounting `/conf` in 3.2

### ISSUE THREAD

**Issue by mpreusse** [neo4j/docker-neo4j#101]
I start neo4j 3.2 community with a docker compose file and mount a local directory to `/conf`. All settings in the `neo4j.conf` file are used except heap space. It is always set to 512M (shown in debug.log and when running `CALL dbms.listConfig()`).

Setting heap space through the environment variable works. Setting the page cache with the conf file also works.

*docker-compose.yml*
```
version: '2'
services:
  neo4j:
    image: neo4j:3.2
    volumes:
      - ./data:/data
      - ./conf:/conf
      - ./import:/import
    ports:
      - "7475:7474"
      - "7689:7687"
```
