### ISSUE TITLE
neo4j image not mounted to volume inappropriately holding data?

### ISSUE THREAD

**Issue by CameronAckermanSEL** [neo4j/docker-neo4j#111]
I have a neo4j docker image defined like so.
```
    test-neo4j:
        image: neo4j:3.1.3
        ports:
        - 7688:7687
        - 7475:7474
        environment:
        - NEO4J_AUTH=none
        labels:
            SERVICE_7474_NAME: neo4j-test
            SERVICE_7687_NAME: neo4j-web-test
```

Previously, the image was not version locked, now it is. Neo4j seems to think that we've downgraded to an older version. But because this image isn't mounted to a volume and I'm not persisting the data, it shouldn't matter.

Now when I try to run this image, I get this error

```
test-neo4j_1   | Caused by: org.neo4j.kernel.impl.storemigration.StoreUpgrader$UnexpectedUpgradingStoreVersionException: Not possible to upgrade a store with version 'v0.A.8' to current store version `v0.A.7` (Neo4j 3.1.3).
```

It seems to me that since this image is not bound to a volume, that it is inappropriately caching the database data. I don't care about this data at all and I would really like it to go away, especially if it solves this issue.

I've tried deleting the image already, and this has not helped.

Thanks.
