### ISSUE TITLE
DB doesn't load plugins

### ISSUE THREAD

**Issue by agalazis** [neo4j/docker-neo4j#112]
After following all the  instructions and mounting a plugin directory containing `apoc-3.3.0.1-all.jar` which is compatible with the neo4j version I use (3.3.0) It won't load them up
The entry point seems to pick /plugins as it lists:
```
neo4j_1  | Directories in use:
neo4j_1  |   home:         /var/lib/neo4j
neo4j_1  |   config:       /var/lib/neo4j/conf
neo4j_1  |   logs:         /var/lib/neo4j/logs
neo4j_1  |   plugins:      /plugins
neo4j_1  |   import:       /var/lib/neo4j/import
neo4j_1  |   data:         /var/lib/neo4j/data
neo4j_1  |   certificates: /var/lib/neo4j/certificates
neo4j_1  |   run:          /var/lib/neo4j/run
```

**Comment by agalazis** [comment]
what I  get instead is: `WARNING: There is no procedure with the name `apoc.export.graphml.all` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`

**Comment by agalazis** [comment]
I will  close this issue since i realised that if put a wrong version of the plugin in the directory it fails to boot so it takes it into account I will open another issue in apoc or neo4j if I figure out the cause.
Having that said also al the configuration gets applied correctly plugin security + apoc import files, end up in the configuration file as well. As a result I concluded that maybe the issue is elsewhere.

**Comment by agalazis** [comment]
reopening because I managed to get my job on non docker version done which means it's not an apoc or neo4j issue. I also tried to mount the same plugin with the same version of neo4j docker image. What remains is to find the cause.

**Comment by agalazis** [comment]
ok managed to get it working in docker using cypher-shell rather than neo4j-shell

**Comment by agalazis** [comment]
Managed to get plugins loaded even in neo4j-shell If you wait long enough they get loaded therefore I ll change the issue title to slow plugin loading

**Comment by manugraj** [comment]
After manually downloading the jar and putting it on plugins folder takes forever for the app to start in docker. The configuration I used is as follows:

```
version: "3"
services:
  neo4j:
    image: neo4j:4.2.6
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/ibs123
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*

```
