### ISSUE TITLE
Unable to probe health when composing

### ISSUE THREAD

**Issue by jpramondon** [neo4j/docker-neo4j#114]
Hello there,

While in the process of preparing a docker-compose, I thought it would be great to make depend my main service on whether my neo4j instance has properly started using the following docker-compose configuration:
```
version: "2.1"

services:
  api:
    ...
    depends_on:
      neo4j:
        condition: service_healthy
    links:
      - neo4j

  neo4j:
    image: neo4j:latest
    ...
    healthcheck:
          test: ["CMD-SHELL", "/var/lib/neo4j/bin/neo4j status"]
          ...
```

the most important options and switches being "depends_on" api service side and "healthcheck" neo4j service side.

The problem I'm facing is that the command "/var/lib/neo4j/bin/neo4j status" always seem to return "Neo4j is not running" with 3 as a return code. The declared "neo4j" service is hence considered as unhealthy and the "api" service is then never started.

After a bit of drilling, I ended up reading [this issue](https://github.com/neo4j/neo4j/issues/9349) on the Neo4j Github repository. It recommends using `systemctl start neo4j` rather than `neo4j start`.

So is there a chance the neo4j image entrypoint changes to `systemctl start neo4j` so the `neo4j status` command could be used for health checking ?

Many thanks for your time !

**Comment by jpramondon** [comment]
The same behaviour may be obtained in a simpler way, by issuing:
`> docker run --rm --health-cmd='/var/lib/neo4j/bin/neo4j status' --health-timeout=10s --health-retries=3 --health-interval=5s neo4j`

Then when one inspects the image, health probing is always like:
```
[
    {
        "Id": "e4d1db80c8cc9f48e0adad54fe7f7e661450e1ae84c5dd7e373db093dbac1421",
        "Created": "2017-11-23T09:40:02.350662078Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "neo4j"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 17999,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-11-23T09:40:02.794463679Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 25,
                "Log": [
                    {
                        "Start": "2017-11-23T10:41:53.97558101+01:00",
                        "End": "2017-11-23T10:41:54.213214128+01:00",
                        "ExitCode": 3,
                        "Output": "Neo4j is not running\n"
                    },
                    {
                        "Start": "2017-11-23T10:41:59.213523563+01:00",
                        "End": "2017-11-23T10:41:59.516092784+01:00",
                        "ExitCode": 3,
                        "Output": "Neo4j is not running\n"
                    },
                    {
                        "Start": "2017-11-23T10:42:04.516274097+01:00",
                        "End": "2017-11-23T10:42:04.762521769+01:00",
                        "ExitCode": 3,
                        "Output": "Neo4j is not running\n"
                    }, 
           ...
```

**Comment by isaacuribe** [comment]
/var/lib/neo4j/bin/neo4j is a shell script, and it is looking for the /var/lib/neo4j/run/neo4j.pid file existence, which won't be there since the whole idea of Docker containers is to run a process (not a full-blown process manager).

I suggest you hit the neo4j browser:

    healthcheck:
      test: curl -i http://127.0.0.1:7474 2>&1 | grep -c -e '200 OK'

Or something else that queries the service itself (like neo4j-shell), not the process wrapper (which is there for non-container-based installations).

**Comment by jpramondon** [comment]
Many thanks for your reply @isaacuribe 

We ended up doing something similar by embedding a "wait-for-it" script into a custom image and performing the health check more or less like so:
```
healthcheck:
          test: ["CMD-SHELL", "/usr/bin/wait-for-it.sh localhost:7687"]
```
Since we're connecting using the bolt protocol, we don't have to wait until the console is ready but consider the imageas being available as soon as the 7687 port is bound.

**Comment by nathanweeks** [comment]
The neo4j:3.5 image has perl, and this one-liner to test if port 7687 is open seems to work as well:
```
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
```
(source: https://stackoverflow.com/a/30031062)

**Comment by joelduerksen** [comment]
For a health check these may be fine, just to know is my neo4j relatively speaking 'more or less" up versus down,
but I can confirm that BOTH the port socket check and "200 OK" will at times return "Success" before Neo4j is ready to use...
(Unless they changed the behavior in a recent release)

For scripting neo4j in docker I've had to resort to waiting until "match (n) return count(n)" returns successfully, to be sure it is actually ready before I start running a series of initialization cypher scripts.

I would like to fall back to something less complicated, this is what my 'wait4neo4j' script does, heavy and ugly but it _works_.

```
# try an actual query as test
docker exec -t \
  --env NEO4J_USERNAME=${NEO4J_USERNAME} \
  --env NEO4J_PASSWORD=${NEO4J_PASSWORD} \
  ${CONTAINER} \
  bash -c "until echo 'match (n) return count(n);' | bin/cypher-shell -a bolt://
localhost:${PORT}; do echo $? ; sleep 1; done"

```

Note: I don't recall if I tried the /var/lib/neo4j/bin/neo4j status approach.

**Comment by steenhansen** [comment]
The Neo4j image I am using has no curl, but it does have wget. The below docker-compose.yml saves me from some ugly polling via a promise retry to see if Neo4j is awake yet.

```
version: "3.6"

services:
  neo4j-db:     
    image: neo4j:3.4.9
	container_name: neo4j__database
    healthcheck:
      test: wget http://neo4j__database:7474/browser -O -
      interval: 1s
      timeout: 1s
      retries: 25 

  node-webserver:   
    image: base-nodejs 
    depends_on:
      neo4j-db:
        condition: service_healthy
```

**Comment by garlab** [comment]
Inspired by @joelduerksen post, my `docker-compose-yml` looks like that:

```yml
    healthcheck:
      test: ["CMD", "cypher-shell", "match (n) return count(n)"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
```

**Comment by SVDouble** [comment]
The answers above didn't work for me, but with some modifications I managed to get the job done:
```yaml
services:
  neo4j:
    image: neo4j:4.4.5
    healthcheck:
      test: [ "CMD", "/var/lib/neo4j/bin/cypher-shell", "-u", "${NEO4J_USERNAME}", "-p", "${NEO4J_PASSWORD}", "MATCH () RETURN count(*) as count" ]
      interval: 10s
      timeout: 10s
      retries: 20
```
