### ISSUE TITLE
Unknown config options

### ISSUE THREAD

**Issue by KevinBurton** [neo4j/docker-neo4j#120]
I am starting the lateest neo4j docker image from DockerHub. When I start the container I get some warnings:
```
neo4j_1  | 2018-01-25 03:30:34.780+0000 WARN  Unknown config option: causal_clustering.transaction_listen_addres
neo4j_1  | 2018-01-25 03:30:34.766+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
neo4j_1  | 2018-01-25 03:30:34.776+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
neo4j_1  | 2018-01-25 03:30:34.776+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
neo4j_1  | 2018-01-25 03:30:34.777+0000 WARN  Unknown config option: ha.host.coordination
neo4j_1  | 2018-01-25 03:30:34.777+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
```

I have a volume bound for the database but I don't know where the configuration file is. It is probably part of the image. The relevant section of the docker-compose.yml file looks like:

```
  neo4j:
    image: neo4j
    ports:
        - "7474:7474"
        - "7687"
    volumes:
      - type: bind
        source: /Users/rebeccaannburton/Projects/AspNetCore-Angular/neo4j/data/db
        target: /data
```

Ideas?

Kevin
