### ISSUE TITLE
Unexpected behavior running two instances with compose

### ISSUE THREAD

**Issue by dantswain** [neo4j/docker-neo4j#133]
I am trying to run two instances of neo4j with compose so that I can have one for development and one for testing.  I'm finding that I'm able to write to both instances via bolt, but the web ui only shows me results from one of them no matter which port I use.

Here is a `docker-compose.yml` file that reproduces this issue:
```
version: '2.1'

services:
  neo4j:
    image: neo4j:3.3.3
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
  neo4jtest:
    image: neo4j:3.3.3
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7475:7474
      - 7688:7687
```

Insert a node into the instance listening on 7687:
```
cypher-shell -a bolt://localhost:7687 "CREATE (:Person {name: 'The Dude'})"
```
Then go to http://localhost:7474/ and execute the cypher `MATCH (n) RETURN n` - it returns this node as expected.  However, I can _also_ go to http://localhost:7475/ and execute the same query and it returns the same result - i.e., it is giving me the result that i inserted into the other container.

I can likewise insert a value in to the instance listening on 7688:
```
cypher-shell -a bolt://localhost:7688 "CREATE (:Person {name: 'Lebowski'})"
```
That node doesn't show up in either UI.

Is there an "advertised address" confusion going on here?  What is the proper setting?  I don't know if there's a way to protect anyone from it or maybe there's just some potential documentation improvement, but this does seem like really confusing "default" behavior.
