### ISSUE TITLE
Circle CI custom neo4j configuration

### ISSUE THREAD

**Issue by devmsh** [neo4j/docker-neo4j#145]
Hi!

We use Neo4j with APOC plugin, and we need to change some configuration by mounting conf volume, and this need a custom run script

```
docker run --rm \
    --volume=$HOME/neo4j/conf:/conf \
    neo4j:3.4 dump-config
```

How can we use the image with this custom run script?

this is a sample of our config.yml:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.3-node-browsers
      # - image: elasticsearch
      - image: digitalcloudsa/neo4j
        environment:
            NEO4J_AUTH=none

    working_directory: ~/repo
```
