### ISSUE TITLE
Setting the password doesn't appear to work

### ISSUE THREAD

**Issue by lukesmurray** [neo4j/docker-neo4j#147]
I've been trying to set an initial password on my Neo4j docker container but it doesn't appear to be doing anything. When I access the container the password is still set to the default which is neo4j. I'm passing in an environment variable based on the documentation I found (here)[https://neo4j.com/docs/operations-manual/current/installation/docker/]. When I try to set the password to something custom the password remains the default neo4j. However, if I say `NEO4J_AUTH=none` then the container respects that and uses no password.

This is the contents of my docker-compose.yml

```
version: "3.7"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./persisted_data/neo4j/data:/data
    ports:
      # http and bolt access respectively
      - 7474:7474
      - 7687:7687
    env_file:
      - .env
```

This is my .env file which works

```
# neo4j auth as username/password
NEO4J_AUTH=none
```

This is my .env file which fails

```
# neo4j auth as username/password
NEO4J_AUTH=neo4j/anything_here_is_replaced_by_neo4j_as_the_password
```
