### ISSUE TITLE
Docker entrypoint disallows seemingly valid usernames

### ISSUE THREAD

**Issue by lmeyerov** [neo4j/docker-neo4j#198]
### Scope

Users of `neo4j/docker-neo4j-publish/blob/master/3.5.9/community` and many earlier versions

Severity is low

### Issue

Setting `NEO4J_AUTH=myuser/mypwd` in a docker compose (or dockerfile) fails with `Invalid value for NEO4J_AUTH`. The behavior is surprising and the message is cryptic and not that constructive.

The expected result is for that user/pwd combo to work. Digging in, it looks like:
* The intended codepath hardcodes user `neo4j`
* The above fails and thus goes down the warning path

### Recommendation

* Normal fix: user `neo4j` to not be hardcoded into https://github.com/neo4j/docker-neo4j-publish/blob/master/3.5.9/community/docker-entrypoint.sh#L295
* Alternative: Error messages with more guidance @ https://github.com/neo4j/docker-neo4j-publish/blob/master/3.5.9/community/docker-entrypoint.sh#L312

**Comment by jennyowen** [comment]
This seems like a case where our documentation could be clearer.

`NEO4J_AUTH` is used to set an **initial** database password, and when the database is first created the only user is always called `neo4j`, so `NEO4J_AUTH` is really only ever used to set a password for the `neo4j` user. This is a constraint on the `set-initial-password` command rather than anything docker specific. 

It's definitely redundant to require that `NEO4J_AUTH` has to begin with `neo4j/` but changing that would break backwards compatibility for many users. I suppose removing the required `neo4j/` prefix would mean that your command `NEO4J_AUTH=myuser/mypwd` would give the `neo4j` user the password `myuser/mypwd` which would also be confusing.

If you're mounting the `/data` volume to an existing database with users already set up, then there's actually no need to set `NEO4J_AUTH`.

As far as I could tell, there's only one paragraph in our documentation about what `NEO4J_AUTH` does, and it's in an untitled subsection of our "volumes" overview: https://neo4j.com/docs/operations-manual/current/docker/introduction/

I think it would be good to improve this. cc @davidoliverSP2

**Comment by jennyowen** [comment]
We discussed this internally and it seems like the best thing to do is to call `neo4j-admin set-default-admin` on the `myuser` part of `NEO4J_AUTH=myuser/mypwd` and call `set-initial-password` on the `mypwd` part.

I'll make that change.

**Comment by Donsky-Osano** [comment]
I'm not mounting a data volume: 
```
  neo4j:
    image: neo4j
    ports:
     - "7474:7474"
     - "7473:7473"
     - "7687:7687"
    environment:
     - NEO4J_PROTOCOL=bolt
     - NEO4J_AUTH=badUsername/badPass
     - NEO4J_HOST=http://localhost
     - NEO4J_PORT=7474
     - NEO4J_USER=badUsername
     - NEO4J_PASSWORD=badPass
     - NEO4J_CREDS=badUsername:badPass
     - NEO4J_INSERT_PATH=file://
    volumes:
     - ./data/neo4j/seeds:/import
    restart: always
```
Any thoughts why I'd be getting this warning and exiting with a
`***_neo4j_1 exited with code 1`
??
