### ISSUE TITLE
Using it in docker-compose

### ISSUE THREAD

**Issue by nanounanue** [neo4j/docker-neo4j#20]
I am trying to use this `image`  with `docker-compose` as follows:

```

graphdb:
  image: neo4j
  volumes:
    - /opt/data
  ports:
    - "7474:7474"
    - "1337:1337"
```

How do I access it from the shell?

How do I set an `username:password`?
