### ISSUE TITLE
Composer ENV VAR Warning "Invalid value for NEO4J_AUTH: 'whatEverThe/EnvVarSays' "

### ISSUE THREAD

**Issue by Donsky-Osano** [neo4j/docker-neo4j#204]
Getting an error with no suggestion on a fix, and can't find what I'm doing wrong in the docs realted to the NEO4J_AUTH env var.

Environment Guidelines:
```
- Mac PowerBook
- OSX 10.15  ( using ZSH, thanks for forcing that on me Apple )
- VSCode terminal ( this actually may make a difference, I'll try after I post this, and just leave a note about it if that's true, but I hope not )
- docker via docker-compose
```

docker-compose.yml 
```
version: '3.7'
  services:
    neo4j:
      image: neo4j
      ports:
       - "7474:7474"
       - "7473:7473"
       - "7687:7687"
      environment:
       - NEO4J_PROTOCOL=bolt
       - NEO4J_AUTH=badUsername/badPass
       - NEO4J_PORT=7474
       - NEO4J_USER=badUsername
       - NEO4J_PASSWORD=badPass
       - NEO4J_CREDS=badUsername:badPass
       - NEO4J_INSERT_PATH=file://
      volumes:
       - "./data/neo4j/seeds:/import"
      restart: always
```

#### Steps to reproduce:

`% docker-compose up --build -d neo4j`

`% docker-compose logs neo4j`

```
Recreating osano-b2b-webservices-api_neo4j_1 ... done
Attaching to osano-b2b-webservices-api_neo4j_1
neo4j_1       | Invalid value for NEO4J_AUTH: 'badUsername/badPass'
neo4j_1       | Invalid value for NEO4J_AUTH: 'badUsername/badPass'
%
```
