### ISSUE TITLE
3.5.14 neo4j.conf: Permission denied

### ISSUE THREAD

**Issue by ainiml** [neo4j/docker-neo4j#223]
Starting `neo4j:3.5.14` you get this error:

`/var/lib/neo4j/bin/neo4j: line 260: /var/lib/neo4j/conf/neo4j.conf: Permission denied`

Related: https://github.com/neo4j/docker-neo4j/issues/207 https://github.com/neo4j/docker-neo4j/issues/131#issuecomment-489612338

**Comment by jennyowen** [comment]
@ainiml I have some questions:

1. What is the docker command you're using to start neo4j? 
1. How can I reproduce your error?
1. what user is the owner of the host folder(s) and what user is docker running as?
1. What group owns the host folder(s) and does the user is docker running as belong to that group?
1. does running docker with `--user="$(id -u):$(id -g)"` fix the problem?

**Comment by ainiml** [comment]
> @ainiml I have some questions:
> 
> 1. What is the docker command you're using to start neo4j?
> 2. How can I reproduce your error?
> 3. what user is the owner of the host folder(s) and what user is docker running as?
> 4. What group owns the host folder(s) and does the user is docker running as belong to that group?
> 5. does running docker with `--user="$(id -u):$(id -g)"` fix the problem?

I'm running it on Rancher

It would be similar to running `docker run -d neo4j:3.5.14`

**Comment by jennyowen** [comment]
@ainiml I'm going to need more to go on I'm afraid, `docker run neo4j:3.5.14` works when I run it.

Permissions errors are almost always caused by mounted folders, there must be a folder mounted somewhere in your setup?

**Comment by anttihietasaari** [comment]
I'm running into the same problem, both with neo4j:3.5 and neo4j:4.0. No mounted volumes or anything, just running plain `docker run neo4j:3.5` causes it to crash with `/var/lib/neo4j/bin/neo4j: line 260: /var/lib/neo4j/conf/neo4j.conf: Permission denied`.

Weirdly enough, the problem appears on our testing server running Ubuntu 16.04 in Amazon EC2, but not on my Ubuntu 18.04 laptop. I also tried running the container inside a Vagrant box with Ubuntu 16.04 and that works fine on my laptop but fails on a coworker's Windows machine.

So, I poked around the container a bit with bash.  Statting the conf file shows 
`Access: (0777/-rwxrwxrwx)  Uid: (  101/   neo4j)   Gid: (  101/   neo4j)` 
and `id` prints 
`uid=101(neo4j) gid=101(neo4j) groups=101(neo4j)`, 
so there's no obvious reason why the file would be unreadable, but `cat conf/neo4j.conf` produces the same permission denied error. I can even create a new file in the conf folder and it has the same permissions and opens just fine - it's just neo4j.conf specifically that's inaccessible.

I did figure out a workaround, though: if you run chmod on the file, that causes it to get "unstuck" and fixes the error, so I can get the image working by running it with 
`docker run neo4j:3.5 bash -c "chmod u+r conf/neo4j.conf && neo4j console"`.
Unfortunately, overriding the start command prevents the NEO4J_AUTH environment variable from applying, so to also set the password you have to do something like 
`docker run neo4j:3.5 bash -c "chmod u+r conf/neo4j.conf && (bin/neo4j-admin set-initial-password YOUR_PASSWORD_HERE; neo4j console)"`

**Comment by ainiml** [comment]
> @ainiml I'm going to need more to go on I'm afraid, `docker run neo4j:3.5.14` works when I run it.
> 
> Permissions errors are almost always caused by mounted folders, there must be a folder mounted somewhere in your setup?

See https://github.com/neo4j/docker-neo4j/issues/223#issuecomment-573689315

**Comment by ainiml** [comment]
Also, Rancher deployment.yaml attached, there are no volumes attached


```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    field.cattle.io/creatorId: u-7pbm6
    field.cattle.io/publicEndpoints: "null"
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-personal-neo4j2
  name: neo4j2
  selfLink: /apis/apps/v1/namespaces/personal/deployments/neo4j2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-personal-neo4j2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-01-14T06:22:53Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-personal-neo4j2
    spec:
      containers:
      - image: neo4j:3.5.14
        imagePullPolicy: Always
        name: neo4j2
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```
