### ISSUE TITLE
Unable to connect to Neo4j using Neo4j browser

### ISSUE THREAD

**Issue by darshanmehta10** [neo4j/docker-neo4j#257]
I have a Neo4j graph with just 100 documents in it. The structure looks like below:

```
"Person" : {
  "id":"string",
  "name":"string",
  "companies":[
    {
      "id":"string",
      "name":string"
    }
  ]
}
```
In the Neo4j browser, when I try to execute the query `match (n:Person) return n limit 10`, it takes long time to respond, eventually times out and returns an error in browser:

```
WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3
```

Neo4j runs in remote node for me (in docker) and I am accessing it from my local machine. As mentioned in [this](https://neo4j.com/developer/kb/how-neo4j-browser-interacts-with-neo4j-server/) link, I have also set `dbms.connector.bolt_listen_address` to `0.0.0.0:7687` for it to accept the remote connections. Below is the docker run command:

```
docker run \
    --name neo4j \
    -p7474:7474 -p7687:7687 \
    -d \
    -v /root/neo4j/data:/data \
    -v /root/neo4j/logs:/logs \
    -v /root/neo4j/import:/var/lib/neo4j/import \
    -v /root/neo4j/plugins:/plugins \
    --env NEO4J_AUTH=neo4j/test \
    --env NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687 \
	neo4j:4.0.4
```

**Neo4j Version:** 4.0.4
**Operating System:** Debian GNU/Linux 10 (buster)
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:4.0.4`
2. Start the container using the above command
3. Add documents as per the structure above
4. Try to query the graph in Neo4j browser

### Expected behavior
Neo4j browser should show the nodes and edges in the graph

### Actual behavior
All the queries fail with the Websocket error described above

**Comment by jennyowen** [comment]
@darshanmehta10 For the Websockets warning, this is the same issue as #240 which has been fixed for Neo4j 4.0.4.
Adding the `--env NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687` argument is probably what's breaking this for you. 
[The instructions you linked to](https://neo4j.com/developer/kb/how-neo4j-browser-interacts-with-neo4j-server/) apply to older versions of Neo4j.

For the second issue about SSL, you haven't enabled port 7473 in docker (at least as far as I can tell from the code you posted) yet you're trying to connect to it in the browser. 
That's not gonna work. You'll need to add the argument `-p 7473:7473`.

**Comment by darshanmehta10** [comment]
@jennyowen thanks for the response. I have updated my docker run command to this:

```
docker run \
    --name neo4j \
    -p7474:7474 -p7687:7687 -p 7473:7473 \
    -d \
    -v /root/neo4j/data:/data \
    -v /root/neo4j/logs:/logs \
    -v /root/neo4j/import:/var/lib/neo4j/import \
    -v /root/neo4j/plugins:/plugins \
    -v /root/neo4j/certificates:/var/lib/neo4j/certificates \
    --env NEO4J_AUTH=neo4j/test \
    --env NEO4J_dbms_connector_https_enabled=true \
    --env NEO4J_dbms_ssl_policy_https_enabled=true \
	neo4j:4.0.4
```

It now exposes the port and does no longer have `NEO4J_dbms_connector_bolt_listen__address` property. However, I still get the same error while trying to access it. Chrome doesn't let me pass through login screen. Do I need to change anything else?

**Comment by rogierc** [comment]
I am getting the same error when running the browser from a remote machine.
When I log into the container and use cypher-shell from within the conatiner, it works.

My compose file:
```
version: "3.3"

volumes:
    neo4j_data:
        external: true
    neo4j_logs:
        external: true

services:
    neo4j:
        container_name: compose_neo4j_1
        build:
            context: ../container
        volumes:
            - type: volume
              source: neo4j_data
              target: /data
            - type: volume
              source: neo4j_logs
              target: /logs
        ports:
            - "7473:7473"
            - "7474:7474"
            - "7687:7687"
        restart: unless-stopped
```
The Dockerfile that is built:
```
FROM neo4j:4.0.4

ENV NEO4J_AUTH=neo4j/test
```
