### ISSUE TITLE
How to correct share between host and the container the `import` folder

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [neo4j/docker-neo4j#293]
Dear all,

I am wondering how to correctly write and read from my host user and the docker neo4j image the `import` folder.

This is my `docker-compose` file

```yml
version: "3"
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $VOLUMES/neo4j/data:/data
      - $VOLUMES/neo4j/plugins:/plugins
      - $VOLUMES/neo4j/logs:/logs
      - ${PWD}/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/test
    network_mode: host
```

When the container starts the `import` folder is created but from my host user I cannot write and read data in it. Is there a possible solution?

Thank you.

Cheers,

Francesco
