### ISSUE TITLE
exit code 143 on graceful shutdown

### ISSUE THREAD

**Issue by gaerfield** [neo4j/docker-neo4j#30]
I'm starting and stopping neo4j with a docker-compose-file:
```
version: '2'
services:
  neo4j:
    image: neo4j:2.3.2
    ports:
      - 7474:7474
    volumes:
      - ./data:/data
```
On `docker-compose stop` I'm getting an '143' exit-code, when the log-messages seems to be fine (console-output from windows docker toolbox):
```
Stopping neo4j_neo4j_1 ...
neo4j_1 | 2016-03-21 09:00:52.599+0000 INFO  Neo4j Server shutdown initiated by request
neo4j_1 | 2016-03-21 09:00:52.643+0000 INFO  Successfully shutdown Neo4j Server
neo4j_1 | 2016-03-21 09:00:52.725+0000 INFO  Successfully stopped database
Stopping neo4j_neo4j_1 ... done
neo4j_neo4j_1 exited with code 143
```
