### ISSUE TITLE
Unable to enable plugins and parse error in console

### ISSUE THREAD

**Issue by jkanche** [neo4j/docker-neo4j#301]
the neo4j service from my docker compose file looks like this 

```
    neo4j:
        image: neo4j:latest
        restart: always
        ports:
            - 7474:7474  
            - 7687:7687 
        environment:
            - NEO4J_AUTH=neo4j/$$$$  
            - NEO4JLABS_PLUGINS='["apoc", "n10s"]'
```

I want to use the neosemantics labs plugin but seem to be running into issues enabling this. I also notice a parse error from the console messages and if this is related to the issue -

```
neo4j_1  | Changed password for user 'neo4j'.
neo4j_1  | parse error: Invalid numeric literal at line 1, column 2
neo4j_1  | 2021-06-16 23:13:46.207+0000 INFO  Starting...
neo4j_1  | 2021-06-16 23:13:48.616+0000 INFO  ======== Neo4j 4.3.0 ========
neo4j_1  | 2021-06-16 23:13:49.993+0000 INFO  org.neo4j.internal.kernel.api.security.AbstractSecurityLog$SecurityLogLine@69ab2d6a
neo4j_1  | 2021-06-16 23:13:49.993+0000 INFO  org.neo4j.internal.kernel.api.security.AbstractSecurityLog$SecurityLogLine@505a8582
neo4j_1  | 2021-06-16 23:13:50.208+0000 INFO  Bolt enabled on 0.0.0.0:7687.
neo4j_1  | 2021-06-16 23:13:51.326+0000 INFO  Remote interface available at http://localhost:7474/
neo4j_1  | 2021-06-16 23:13:51.330+0000 INFO  Started.
```

I appreciate any help with trying to run neosemantics
