### ISSUE TITLE
Neo4j fails with APOC plugin enabled

### ISSUE THREAD

**Issue by robomotic** [neo4j/docker-neo4j#315]
Hi folks,
trying to figure out why this fails with exit code 1.

```
version: '3'
# https://neo4j.com/developer/docker-run-neo4j/
services:
  neo4j_gds:
    image: neo4j:4.3.7-community
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/new4j
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
```

But removing APOC plugin deploys correctly.

```
version: '3'
# https://neo4j.com/developer/docker-run-neo4j/
services:
  neo4j_gds:
    image: neo4j:4.3.7-community
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/new4j
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
```

Let me know how can I find the issue, I don't see much from the logs just an Exit with code 1.
