### ISSUE TITLE
Random exits

### ISSUE THREAD

**Issue by coeus01** [neo4j/docker-neo4j#32]
Hello, I'm using neo4j in a docker-compose project and sometimes I need to start the neo4j docker 3-4 times in order to stay up and it randomly exits (Exited (137)) sometimes after 3 days, sometimes after 3 hours. The same thing happens for `docker-compose up` as well as `docker start project_db`, the other services that I have along are working as expected.

docker-compose.yml
```
version: '2'   
services:   
    db:   
        image: neo4j   
        ports:   
            - "7474:7474"   
        volumes:   
            - "./data:/data"   
        environment:   
            NEO4J_AUTH: "neo4j/neo4j"   
```
