### ISSUE TITLE
Close immediately after change password log

### ISSUE THREAD

**Issue by A-Siam** [neo4j/docker-neo4j#327]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
If you have questions on how to use Neo4j, please ask on [Neo4j Community](https://community.neo4j.com/) or [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

To help us understand your issue, please specify important details, primarily:

- **Steps to reproduce**. 
- I've written this docker-compose
```
  neo4j:
    image: neo4j:4.4.0
    environment:
      - NEO4J_AUTH=neo4j/pass
    volumes:
      - ./persistance/data:/data
      - ./persistance/logs:/logs
      - ./persistance/import:/var/lib/neo4j/import
      - ./persistance/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
```
- **Expected behavior**: to start normally
- **Actual behavior**: 
```
neo4j_1         | Changed password for user 'neo4j'.
tst-api_neo4j_1 exited with code 1
```
- ***Neo4j image tag being used, eg `neo4j:latest`, `neo4j:enterprise-3.5` etc**: `neo4j:4.4.0`
- The output of the `docker version` command: `Docker version 20.10.12, build e91ed57`
- **Host operating system**: `ubuntu 20.04`

**Additionally, include (as appropriate) log-files, stacktraces, and other debug output**: the `/logs/debug.log` is empty
