### ISSUE TITLE
Choose which local port to start

### ISSUE THREAD

**Issue by igorescobar** [neo4j/docker-neo4j#34]
Would be nice to have a environment variable in order to choose which local port the service should start.

**The problem**:
If you are in a development/testing environment the service will always start using the port `7474`. If you want to have two neo4j containers one running at `7474` and another one at `7475` (sharing the same host) you can't because this port are pretty much hard coded inside of the `docker-entrypoint.sh`. This is pretty much a common use case when using it along with `docker-compose` because you basically don't want to mix your development data and your automated testing data.

If you take a look at the docs you are proposing a solution using docker networks and HAProxies like this one:
```
docker network create --driver=bridge cluster

docker run --name=instance1 --detach --publish=7474:7474 --net=cluster --hostname=instance1 \

    --env=NEO4J_DATABASE_MODE=HA --env=NEO4J_HA_ADDRESS=instance1 --env=NEO4J_SERVER_ID=1 \

    --env=NEO4J_INITIAL_HOSTS=instance1:5001,instance2:5001,instance3:5001 \

    neo4j:enterprise-2.3



docker run --name=instance2 --detach --publish 7475:7474 --net=cluster --hostname=instance2 \

    --env=NEO4J_DATABASE_MODE=HA --env=NEO4J_HA_ADDRESS=instance2 --env=NEO4J_SERVER_ID=2 \

    --env=NEO4J_INITIAL_HOSTS=instance1:5001,instance2:5001,instance3:5001 \

    neo4j:enterprise-2.3



docker run --name=instance3 --detach --publish 7476:7474 --net=cluster --hostname=instance3 \

    --env=NEO4J_DATABASE_MODE=HA --env=NEO4J_HA_ADDRESS=instance3 --env=NEO4J_SERVER_ID=3 \

    --env=NEO4J_INITIAL_HOSTS=instance1:5001,instance2:5001,instance3:5001 \

    neo4j:enterprise-2.3
``` 

I don't know about you but I couldn't make it work correctly with `docker-compose` and I also thinks that for development/testing purposes its pretty much a "bazooka to kill an ant".

**Proposed Solution**:
My docker-compose.yml would look like:

```yml
neo4j:
  image: neo4j
  ports:
    - "7474"
  environment:
    NEO4J_AUTH: none
neo4j-test:
  image: neo4j
  ports:
    - "7475"
  environment:
    NEO4J_AUTH: none
    NEO4J_PORT: 7575
```
Notice the `NEO4J_PORT` env variable.

And my neo4j.yml would look like:
```yml
development:
  type: server_db
  url: http://neo4j:7474

test:
  type: server_db
  url: http://neo4j-test:7475
```

I may be wrong but looks like its pretty much like adding a
`setting "org.neo4j.server.webserver.port" "${NEO4J_PORT:7474}" neo4j-server.properties` to `docker-entrypoint.sh` and another few simple tweaks.

What are your thoughts?

**Comment by benbc** [comment]
@igorescobar The bit of the docs that you mention is for running Neo4j clusters where the instances need to talk to each other. Is that what you are doing? If you are just running standalone instances there is certainly no need for Docker networks.

**Comment by benbc** [comment]
@igorescobar Assuming that you are running standalone instances, I don't understand the problem that you are facing. You should be able to use Docker's standard port mapping mechanism to publish Neo4j's default `7474` on any port you like within the Docker host.

You can expose Neo4j on the host's port `1234` like this using "raw" Docker:

```
docker run --publish=1234:7474 neo4j
```

Or like this using `docker-compose`:

```yaml
neo4j:
  image: neo4j
  ports:
    - "1234:7474"
```

Does that solve your problem?

**Comment by spacecowboy** [comment]
@igorescobar here is a docker-compose file which works, and starts a 3-node HA-cluster. It essentially implements what @benbc suggests, and each instance's browser is available to look at `7474`, `7475`, and `7476`, respectively.

I also had to turn off `Use bolt by default` in the browser for member1 , or expose the commented out port.

```yml
version: '2'
services:

  member1:
    image: neo4j
    ports:
      - "7474:7474"
      #- "7687:7687"
    networks:
      - basic-lan
    environment:
      - NEO4J_SERVER_ID=1
      - NEO4J_HA_ADDRESS=member1
      - NEO4J_PUBLIC_HOST=member1
      - NEO4J_DATABASE_MODE=HA
      - NEO4J_AUTH=none
      - NEO4J_INITIAL_HOSTS=member1:5001,member2:5001,member3:5001

  member2:
    image: neo4j
    ports:
      - "7475:7474"
    networks:
      - basic-lan
    environment:
      - NEO4J_SERVER_ID=2
      - NEO4J_HA_ADDRESS=member2
      - NEO4J_PUBLIC_HOST=member2
      - NEO4J_DATABASE_MODE=HA
      - NEO4J_AUTH=none
      - NEO4J_INITIAL_HOSTS=member1:5001,member2:5001,member3:5001

  member3:
    image: neo4j
    ports:
      - "7476:7474"
    networks:
      - basic-lan
    environment:
      - NEO4J_SERVER_ID=3
      - NEO4J_HA_ADDRESS=member3
      - NEO4J_PUBLIC_HOST=member3
      - NEO4J_DATABASE_MODE=HA
      - NEO4J_AUTH=none
      - NEO4J_INITIAL_HOSTS=member1:5001,member2:5001,member3:5001

networks:
  basic-lan:
    ipam:
      config:
        - subnet: 192.168.36.0/24
          ip-range: 192.168.36.0/24
```
The docker network settings are unnecessarily specific with regards to ip-subnet and so forth so change those however you like.

**Comment by igorescobar** [comment]
@spacecowboy Thanks for sharing your `docker-compose-yml` with me! I will for sure keep it to use in a future but as I said... for now I think it is a bit too much for testing/development.

@benbc  and thanks for your prompt answer, very appreciated!

Your solution works fine if you are only using docker and creating standalone containers. When we are working with `docker-compose` we sort of compose our environments with another containers and their are able to communicate with other using their internal ports.

The following recipe is using the suggestion you did:
```yml
db:
  image: postgres:9.4.5
  ports:
    - "5432"
neo4j:
  image: neo4j
  ports:
    - "7474:7474"
  environment:
    NEO4J_AUTH: none
neo4j-test:
  image: neo4j
  ports:
    - "7475:7474"
  environment:
    NEO4J_AUTH: none
redis:
  image: redis:2.8.23
  ports:
    - "6379"
web:
  build: .
  command: bundle exec rails s -p 9000 -b '0.0.0.0'
  environment:
    BUNDLE_JOBS: 2
    PORT: 9000
  links:
    - db:db
    - neo4j:neo4j
    - neo4j-test:neo4j-test
    - redis:redis
  ports:
    - "9000:9000"
  volumes:
    - ./:/usr/src/app
    - ./vendor/bundle:/bundle
```
This is the command I use to run it:
`docker-compose run  --rm --service-ports web bash`

And what happens is:
- Externally I can access both neo4j containers just fine, I opened the browser and everything is there...
- BUT from inside of your application container the port 7574 doesn't exist.

For example,  my host has the IP: `192.168.99.100`. I can only access my second container from that ip, like: 192.168.99.100:7574 but from the inside of the container all communication goes via: `tcp://172.17.0.4:7474`. I could explicitly tells my container use the host´s IP instead of the local IP but it would be a little `hacky` because docker-compose not even inject a environment variable to be used by our containers so that would be a little weird because would need a pre-setup before running the `docker-compose.yml`.

If I could choose those ports as proposed this problem

**Comment by benbc** [comment]
@igorescobar Why do you need to access Neo4j from within its own container?

**Comment by igorescobar** [comment]
@benbc this is my `neo4j.yml`:
```yml
development:
  type: server_db
  url: http://neo4j:7474

test:
  type: server_db
  url: http://neo4j-test:7475
```

Which means that when my `RAILS_ENV=development` I will be connected to the container `neo4j:7474`. and When ran my suit tests like `bundle exec rspec` it will be connected to the container `neo4j-test:7475`. The major problem in sharing the same container is that I don't want to mix both data. For the same reasons you have a db_development and a db_test inside of your application. This is a pretty common use case for any kind of service like redis, memcached, postgres and so on... And also... this is pretty much the main reason why would would use `docker-compose` instead of pure `docker` commands.

**Comment by igorescobar** [comment]
@benbc In order to understand a little better what docker-compose help us... its pretty much like this.. when you compose your application environment it injects hosts in your `/etc/hosts/` like:
![screen shot 2016-05-25 at 12 06 50](https://cloud.githubusercontent.com/assets/24032/15537988/5a34be96-2271-11e6-8d3b-aec39ef79bbd.png)

Also inject environment variables so you can use them from inside of your application container:
![screen shot 2016-05-25 at 12 07 05](https://cloud.githubusercontent.com/assets/24032/15538011/716737a6-2271-11e6-922c-786b2b170b9a.png)

**Comment by spacecowboy** [comment]
@igorescobar I am a bit confused as to why you need to change the port for the test database.

Inside your `web` container, the test database is available at `neo4j-test` and the production db at `neo4j`, which resolve to different containers with different ip addresses.

Can your app not simply use different hostnames depending on prod/test environment?

**Comment by igorescobar** [comment]
@spacecowboy it looks like they are diffrent but at the bottom they are the same. it still being redirect to the same container in the end, same container, same port, same host, same partition, same everything.

**Comment by igorescobar** [comment]
But I guess I was wrong... maybe it is harder that it looks to choose which port to start the server... 😞

**Comment by spacecowboy** [comment]
@igorescobar It's not that choosing which port to start is hard (you can just add a config volume and specify it to your liking), but I think that's solving the wrong problem here.

> it looks like they are diffrent but at the bottom they are the same

They should most definitely not be the same. What is the "bottom" we are talking about here? I'd be happy to try some stuff out locally and give you a working config if I have some more details on how your app tries to connect to neo4j in prod/test.

**Comment by igorescobar** [comment]
@spacecowboy its pretty simple. I want to be able to have different data in my development environment and my testing environment. Pretty much the same outcome as using a postgres database, where my connection URL would be like: `postgres://postgres@db/myDb_development` and `postgres://postgres@db/myDb_test`... In that case we are using the same postgres but there is no data being shared between those environments.

Imagine the following docker-compose file:
```yml
neo4j:
  image: neo4j
  ports:
    - "7474:7474"
  environment:
    NEO4J_AUTH: none
neo4j-test:
  image: neo4j
  ports:
    - "7475:7474"
  environment:
    NEO4J_AUTH: none
web:
  build: .
  links:
    - neo4j:neo4j
    - neo4j-test:neo4j-test
  ports:
    - "9000:9000"
  volumes:
    - ./:/usr/src/app
    - ./vendor/bundle:/bundle
```

Run `docker-compose run  --rm --service-ports web bash`.

if you were able to get inside of the `web` container, import data `X` into `7474` neo4j container... and import data `Y` into `7475` container in which DATA `X` can not exists inside of `7475` and `Y` can not exists into `7474` (without using the external IP). This means that you succeed in this quest. :)

**Comment by spacecowboy** [comment]
Easy peasy. Here's the docker-compose file I use:

```yml
version: '2'
services:

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
    networks:
      - basic-lan
    environment:
      - NEO4J_AUTH=none

  neo4j-test:
    image: neo4j
    ports:
      - "7475:7474"
    networks:
      - basic-lan
    environment:
      - NEO4J_AUTH=none

  web:
    image: debian
    networks:
      - basic-lan

networks:
  basic-lan:
    ipam:
      config:
        - subnet: 192.168.37.0/24
          ip-range: 192.168.37.0/24
```

First, I get all the containers up and running:

```
docker-compose up
```

Then, I start a bash session in the web container 

```
docker-compose run web bash
```

All the rest is typed into the bash session.

We need curl for the example:

```
apt-get update && apt-get install curl
```

Once done, let's create two nodes in the prod database:

```
curl -X POST -H Accept:application/json -v neo4j:7474/db/data/node
curl -X POST -H Accept:application/json -v neo4j:7474/db/data/node
```

and four in the test database (note host and port here):

```
curl -X POST -H Accept:application/json -v neo4j-test:7474/db/data/node
curl -X POST -H Accept:application/json -v neo4j-test:7474/db/data/node
curl -X POST -H Accept:application/json -v neo4j-test:7474/db/data/node
curl -X POST -H Accept:application/json -v neo4j-test:7474/db/data/node
```

Done. Open the browser and view the result:

Production (localhost:7474):

![selection_042](https://cloud.githubusercontent.com/assets/223655/15560553/ecd5fd8e-22ec-11e6-9bc0-a7f8bced76c7.png)


And Test (localhost:7475):

![selection_043](https://cloud.githubusercontent.com/assets/223655/15560557/fcda9a28-22ec-11e6-89f5-8f39855a4a32.png)

It is of course a trivial matter to replace the Curl statements with some actual code importing real data.
