### ISSUE TITLE
Images seem to break on a regular basis

### ISSUE THREAD

**Issue by adadgio** [neo4j/docker-neo4j#388]
## Guidelines

Images do not seem to be stable, two examples. We use images in github actions like such : 

neo4j:4.2.4
or 
neo4j:latest

With the following setup

```
services:
      neo4j:
        image: neo4j:4.2.4
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: "neo4j/abcde"
          NEO4JLABS_PLUGINS: '["graph-data-science", "apoc"]'
        options: >-
          --name neo4j-e2e
          --health-cmd "cypher-shell -u neo4j -p abcde 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-start-period 10s
          --health-retries 5
        ports:
          - 7687:7687
       cyphershell:
        image: neo4jbuildservice/cypher-shell-build
        env:
          NEO4J_AUTH: "neo4j/abcde"
```

One day, the image works, the other days, we can get the following errors  without changing anything in our code

With neo4j:4.2.4 : Error: Failed to initialize, neo4j service is unhealthy.
With neo4j:latest: apoc.xxx procedure not found
