### ISSUE TITLE
Downloaded Plugin (APOC) File Permission

### ISSUE THREAD

**Issue by saeedseyfi** [neo4j/docker-neo4j#420]
**Expected behaviour:**
Neo4j takes ownership of downloaded plugin file after install. Even if the plugin directory is mounted.

**Actual behaviour:**
Currently if the plugins directory is mounted APOC plugin installation fails during docker compose up:
```
❯ docker compose up
[+] Running 6/6
 ⠿ neo4j Pulled                                                                                                                                         25.0s
   ⠿ 934ce60d1040 Pull complete                                                                                                                          5.7s
   ⠿ 7af213950f8c Pull complete                                                                                                                         21.3s
   ⠿ 89a47ca77276 Pull complete                                                                                                                         21.4s
   ⠿ 76fb7786289d Pull complete                                                                                                                         21.4s
   ⠿ 2f5e812311c5 Pull complete                                                                                                                         22.0s
[+] Running 2/2
 ⠿ Network reproduce-neo4j-perm_ecosystem_network  Created                                                                                               0.0s
 ⠿ Container neo4j                                 Created                                                                                               0.3s
Attaching to neo4j
neo4j  | Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
neo4j  | Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
neo4j  | Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
neo4j  | Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
neo4j exited with code 1
```

<details>
  <summary>docker-compose.yaml</summary>
  
  ```yaml
version: '3'
services:
  neo4j:
    image: neo4j:5-community
    container_name: neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/logs:/var/lib/neo4j/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/var/lib/neo4j/plugins # problematic
    environment:
      - NEO4J_server.memory.pagecache.size=1G
      - NEO4J_server.memory.heap.max_size=1G
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - ecosystem_network

networks:
  ecosystem_network:
    driver: bridge
  ```
</details>

**Neo4j image tag being used: 5-community**

**docker version**
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.14.1 (91661)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**docker compose version**
```
Docker Compose version v2.12.2
```

**OS**
macOs: 13.1 (22C65) Ventura
Apple M1 Max
```
Darwin SYS 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```
