### ISSUE TITLE
Error using or configuring APOC in GithubAction

### ISSUE THREAD

**Issue by AdrianPardo99** [neo4j/docker-neo4j#424]
## Guidelines

Error trying to install neo4j:4.4.9 and using APOC plugin in gitaction

To help us understand your issue, please specify important details, primarily:

- When I test my pull request in github the following tests show me the next error message in django

```
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Unknown function 'apoc.convert.toJson'
```

- And I build image like and next lines configure the environment for test with python and django correctly, it wants to reproduce my docker-compose file but i had the same error when I try to run all unit tests cases:

```
jobs:
  test:
    runs-on: ubuntu-latest
    services: # Service containers to run with `test`
      # Label used to access the service container
      neo4j:
        # Docker Hub image
        image: neo4j:4.4.9
        # Provide the password for neo4j
        env:
          NEO4J_AUTH: "neo4j/neo4j_password"
          NEO4J_dbms_connector_bolt_enabled: "true"
          NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
          NEO4JLABS_PLUGINS: "['apoc']"
        ports:
          - 7687:7687
```

Is missing something in my configuration or I'm losing something for configuration?
