### ISSUE TITLE
conf folder not persisted

### ISSUE THREAD

**Issue by couardcourageux** [neo4j/docker-neo4j#494]
# the docker compose file

```yml
version: '3'

services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 2s
      retries: 15
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j_db/conf:/conf
      - ./neo4j_db/data:/data
      - ./neo4j_db/import:/import
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/password
```
# The problems

## The Auth problem
> Almost every time i restart the container, i have auth issues

## The conf problem
> Whatever i do, the conf folder on my machine is not populated, unlike data and logs. Hence, i don't understand how the conf, thus the password, is persisted
