### ISSUE TITLE
Neo4j 4.4.38-community docker image contains breaking changes

### ISSUE THREAD

**Issue by Duppils** [neo4j/docker-neo4j#518]
- Neo4j version: 4.4.38-community
- Operating system: maven:3-jdk-11-slim
- API: Docker

I have confirmed that locking our version to 4.4.37 resolved the issue.

- **Steps to reproduce**

(written in pseudo code, you may need to make minor adjustments)

1. Setup docker-compose:

docker-compose.yml:

```
dc-neo4j:
    image: neo4j:4.4.38-community
    container_name: dc-neo4j
    build:
      context: .
      environment:
          - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
          - NEO4JLABS_PLUGINS=["apoc"]
      volumes:
          - ./neo4j/data:/data
       ports:
          - 7474:7474
          - 7687:7687
```

The variables used for neo4j:

```
- NEO4J_PASSWORD=xyz
- NEO4J_NAME_DB=neo4j
```

2. Try to build and connect to the container

- Expected behavior
neo4j docker container can be built and started as in previous versions.

- Actual behavior
The following error messages:

```
WARNING: Service runner-abcd-concurrent-0--gitlab.company.com__neo4j-production probably didn't start properly.

Service container logs:
stat: unrecognized option '-----BEGIN CERTIFICATE----- [Secrets] -----END CERTIFICATE-----'
does not exist or is not readable. Make sure you have correctly configured docker secrets.
```

Let me know if there is any more information I can provide to help find the issue. The code I'm working with isn't open source, so I wanted to avoid sharing too much.

Extra info:
Problem happened running with Gitlab CI, haven't tested other ways. Running with `gitlab-runner 17.1.0`.

I assume it's related to secrets since it was mentioned in the logs and is also a part of the latest changelogs:

```
Docker
* Add support for docker secrets
```

https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog
