### ISSUE TITLE
Mapping an existing local neo4j database to a neo4j docker container [OSX]

### ISSUE THREAD

**Issue by Alexjajones** [neo4j/docker-neo4j#66]
I seem to be having troubles mapping a local database to the docker container. I have exhausted google and stackoverflow after hours of search and still can't get it working. Im wondering if there's an issue or am I just barking up the wrong tree.

Here is my docker-compose.yml:

```
version: '2'
services:
  neo4j:
    image: neo4j
    ports:
     - "7474:7474"
    volumes:
      - /User/testuser/Documents/Neo4j/epe.graphdb/data:/data
    environment:
       NEO4J_AUTH: neo4j/neo4j
```
 
When using the desktop application for neo4j, setting the database location to the following works perfect and I can browse the data. But the browser within the docker container returns no data.

`/User/testuser/Documents/Neo4j/epe.graphdb`

Sorry if this is just me being stupid, close if this is the case.
