### ISSUE TITLE
Latest image (community/3.1.2) can't be restarted after being stopped on docker-compose

### ISSUE THREAD

**Issue by dsolmirano** [neo4j/docker-neo4j#78]
Environment: Mac (Docker for Mac stable channel installed).

Create `docker-compose.yml` file with:

```
neo4j3-data:
  image: busybox
  volumes:
    - /data

#Neo4J database engine
neo4j3-engine:
  image: neo4j:latest
  volumes_from:
    - neo4j3-data
  ports:
    - "7474:7474"
    - "7473:7473"
    - "7687:7687"
  expose:
    - "7474"
    - "7473"
    - "7687"
  environment:
    - NEO4J_AUTH=neo4j/testpassword
```

Start docker machines:
`docker-compose up`

neo4j image starts correctly.

Stop the machine

Start machines again:
`docker-compose up`

Machine fails to start with message:
`Initial password was not set because live Neo4j-users were detected`

With image 3.1.1, there's a warning: `Warning: Initial password was not set because live Neo4j-users were detected, so the initial password has no effect.` but the image restarts correctly.

Same steps can be obtained with docker... although it seems that neo4j:latest doesn't pull 3.1.2 directly?

```
$docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --env=NEO4J_AUTH=neo4j/testpassword neo4j:latest
Warning: Initial password was not set because live Neo4j-users were detected, so the initial password has no effect.
Starting Neo4j.
2017-03-15 17:41:34.351+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2017-03-15 17:41:35.326+0000 INFO  Starting...
2017-03-15 17:41:36.026+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2017-03-15 17:41:40.416+0000 INFO  Started.
2017-03-15 17:41:41.822+0000 INFO  Remote interface available at http://localhost:7474/
```

```
$docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --env=NEO4J_AUTH=neo4j/testpassword neo4j:3.1.2 
Unable to find image 'neo4j:3.1.2' locally
3.1.2: Pulling from library/neo4j
627beaf3eaaf: Pull complete 
1de20f2d8b83: Pull complete 
74e619d34827: Pull complete 
2b3f029f8f8c: Pull complete 
5c1be074b03c: Pull complete 
c39fa1958707: Pull complete 
da1a02f2fbbd: Pull complete 
5a1124342a43: Pull complete 
Digest: sha256:017761cba57d4a117507393cdf68cfc73113978f1395cc34dfb9fd881088b7d6
Status: Downloaded newer image for neo4j:3.1.2
command failed: initial password was not set because live Neo4j-users were detected.

```

**Comment by spacecowboy** [comment]
Thanks for the report. We'll get this fixed asap

**Comment by jdrain** [comment]
I am having the same issue running docker-compose with a neo4j-3.3.0 (latest) image. I am using Ubuntu 16.04 LTS.

docker-compose.yml:

```
version: "3"

services:

  neo4j:
    image: neo4j
    ports:
      - "7474:7474" # browser interface, may be unneccesary
      - "7687:7687" # bolt connection
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    volumes:
      - "neo4j:/var/lib/neo4j/data"

  node_webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${SERVER_PORT}
      - MONGO_URL=mongo
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/var/lib/mongo_data"

volumes:

  mongodb:
  neo4j:
```
 
Everything starts up, but I get nearly the same error as @dsolmirano 

`command failed: initial password was not set because live Neo4j-users were detected.`

Interestingly, this only occurs with docker-compose. If I run:

```
docker run --publish=7474:7474 --publish=7687:7687 \
--env=NEO4J_AUTH=neo4j/$NEO4J_PASSWORD neo4j
```

Everything works as suspected.

Any help would be much appreciated!
