### ISSUE TITLE
Causal clustering is not configurable with Docker service name (swarm mode)

### ISSUE THREAD

**Issue by jarellm** [neo4j/docker-neo4j#87]
I'm currently testing out the causal clustering feature in Docker swarm mode primarily with a docker-compose file and the command: 

`docker stack up -c compose-neo4j-master.yml neo4j`

Ideally, the most concise "swarm mode way" to deploy the 3 core cluster nodes would be this:

```
services:
  neo4jcore:
     - NEO4J_dbms_mode=CORE
     - NEO4J_causalClustering_expectedCoreClusterSize=3
     - NEO4J_causalClustering_initialDiscoveryMembers=neo4jcore:5000
     deploy:
        replicas: 3
```

The  `neo4jcore:5000` part leverages the built-in DNS resolution and routing mesh within the neo4jcore service, so I wouldn't have to know the hostname/IP of each task container spawned by Docker.

However, running this configuration stops at

`Attempting to connect to the other cluster members before continuing..`

I haven't dug in the code, but I'm assuming either the expected count will never reach 3 because only 1 host was declared OR the load balancing provided by the docker swarm is getting in the way for core member nodes to properly do handshakes.

What did work for me is to do something similar to your test file [causal-cluster-compose.yml](https://github.com/neo4j/docker-neo4j/blob/master/test/causal-cluster-compose.yml) and manually spread the services to different nodes.

```
services:
  neo4jcore1:
     - NEO4J_dbms_mode=CORE
     - NEO4J_causalClustering_expectedCoreClusterSize=3
     - NEO4J_causalClustering_initialDiscoveryMembers=neo4jcore1:5000,neo4jcore2:5000,neo4jcore3:5000
     deploy:
        replicas: 1
        placement:
          constraints:
             - node.hostname=node1
  neo4jcore2:
     - NEO4J_dbms_mode=CORE
     - NEO4J_causalClustering_expectedCoreClusterSize=3
     - NEO4J_causalClustering_initialDiscoveryMembers=neo4jcore1:5000, neo4jcore2:5000,neo4jcore3:5000
     deploy:
        replicas: 1
        placement:
          constraints:
             - node.hostname=node2
  neo4jcore3:
     - NEO4J_dbms_mode=CORE
     - NEO4J_causalClustering_expectedCoreClusterSize=3
     - NEO4J_causalClustering_initialDiscoveryMembers=neo4jcore1:5000, neo4jcore2:5000,neo4jcore3:5000
     deploy:
        replicas: 1
        placement:
          constraints:
             - node.hostname=node3
```

It would be great if neo4j/neo4j-docker played nice with this feature and supported it right out of the box. 
Also by supporting this, clients can use a common connection string (e.g. bolt+routing://neo4jcore:7687)
without much configuration/reverse proxy help.

I'm thinking if it can generate the IP address list for the option `NEO4J_causalClustering_initialDiscoveryMembers` by doing nslookup on an intermediate environment variable declared in the compose file.
